export interface FriendsConversationStep {
  side: 'left' | 'right';
  message: string;
}

export const FRIENDS_CONVERSATION_SCRIPT: ReadonlyArray<FriendsConversationStep> = [
  { side: 'left', message: 'omw' },
  { side: 'right', message: 'wya?' },
  { side: 'left', message: 'still home' },
  { side: 'left', message: 'lol' },
  { side: 'right', message: 'same' },
  { side: 'right', message: '\u{1F62D}\u{1F62D}' },
  { side: 'left', message: 'logging soon' },
  { side: 'right', message: 'pc booting' },
  { side: 'left', message: 'wifi slow' },
  { side: 'right', message: 'of course' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'coffee first' },
  { side: 'right', message: 'priorities' },
  { side: 'left', message: 'u ate?' },
  { side: 'right', message: 'barely' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'dangerous' },
  { side: 'right', message: 'living wild' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'what time' },
  { side: 'right', message: '5 mins' },
  { side: 'left', message: 'u swear?' },
  { side: 'right', message: 'mostly' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: '\u{1F644}' },
  { side: 'right', message: 'dont judge' },
  { side: 'left', message: 'headphones?' },
  { side: 'right', message: 'charging' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'again??' },
  { side: 'right', message: 'listen' },
  { side: 'right', message: '\u{1F62D}\u{1F62D}' },
  { side: 'left', message: 'always u' },
  { side: 'right', message: 'I KNOW' },
  { side: 'left', message: 'im ready' },
  { side: 'right', message: 'not yet' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'shocker' },
  { side: 'right', message: 'one sec' },
  { side: 'left', message: 'u said that' },
  { side: 'right', message: 'different sec' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'lies' },
  { side: 'right', message: 'truth-ish' },
  { side: 'left', message: 'launching game' },
  { side: 'right', message: 'updating' },
  { side: 'right', message: '\u{1F480}\u{1F480}' },
  { side: 'left', message: 'NOOO' },
  { side: 'right', message: '\u{1F602}\u{1F602}' },
  { side: 'left', message: 'how long' },
  { side: 'right', message: 'estimating' },
  { side: 'left', message: 'dont say it' },
  { side: 'right', message: '12 mins' },
  { side: 'right', message: '\u{1F62D}\u{1F62D}\u{1F62D}' },
  { side: 'left', message: 'im screaming' },
  { side: 'right', message: 'im sorry' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'queue snacks' },
  { side: 'right', message: 'emotional support' },
  { side: 'left', message: 'valid' },
  { side: 'right', message: 'send memes' },
  { side: 'left', message: 'already did' },
  { side: 'right', message: 'im crying' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'update moved' },
  { side: 'right', message: 'to 15' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'i quit' },
  { side: 'right', message: 'pls dont' },
  { side: 'left', message: 'too late' },
  { side: 'right', message: 'lying' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'ok fine' },
  { side: 'right', message: 'thank god' },
  { side: 'left', message: 'u alive' },
  { side: 'right', message: 'barely' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'fan loud' },
  { side: 'right', message: 'jet engine' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'pc fighting' },
  { side: 'right', message: 'losing battle' },
  { side: 'left', message: 'any percent' },
  { side: 'right', message: '93%' },
  { side: 'left', message: 'DONT MOVE' },
  { side: 'right', message: 'IM NOT' },
  { side: 'right', message: '\u{1F62D}' },
  { side: 'left', message: 'last time' },
  { side: 'right', message: 'I KNOW' },
  { side: 'left', message: 'ok ready' },
  { side: 'right', message: 'WAIT' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'WHAT' },
  { side: 'right', message: 'restart' },
  { side: 'right', message: '\u{1F62D}\u{1F62D}' },
  { side: 'left', message: 'im done' },
  { side: 'right', message: 'PLEASE' },
  { side: 'left', message: 'deep breaths' },
  { side: 'right', message: 'hyperventilating' },
  { side: 'left', message: 'ok go' },
  { side: 'right', message: 'LAUNCHED' },
  { side: 'left', message: 'actually?' },
  { side: 'right', message: 'ACTUALLY' },
  { side: 'left', message: 'invite me' },
  { side: 'right', message: 'sent' },
  { side: 'left', message: 'loading' },
  { side: 'right', message: 'dont crash' },
  { side: 'left', message: 'promise?' },
  { side: 'right', message: 'no promises' },
  { side: 'right', message: '\u{1F480}' },
  { side: 'left', message: 'im in' },
  { side: 'right', message: 'ME TOO' },
  { side: 'left', message: 'finally' },
  { side: 'right', message: 'after years' },
  { side: 'right', message: '\u{1F62D}\u{1F62D}' },
  { side: 'left', message: 'worth it' },
  { side: 'right', message: 'barely' },
  { side: 'right', message: '\u{1F602}\u{1F480}' },
];
