import * as THREE from 'three';

export const FRIENDS_DOT_APPEAR_DURATION = 0.3;
export const FRIENDS_DOT_PAUSE_DURATION = 0.2;
export const FRIENDS_TYPING_SIGN_DURATION = 5.0;
export const FRIENDS_TYPING_INDICATOR_HEIGHT = 24;
export const FRIENDS_TYPING_INDICATOR_WIDTH = 40;
export const FRIENDS_TYPING_INDICATOR_BODY_HEIGHT = 20;
export const FRIENDS_MESSAGE_TRANSLATE_DURATION = 0.3;
export const FRIENDS_MESSAGE_DISPLAY_DURATION = 6.0;
export const FRIENDS_MESSAGE_FADE_DURATION = 0.5;
export const FRIENDS_MESSAGE_MAX_STACK = 3;
export const FRIENDS_MESSAGE_PARENT_WIDTH = 200;
export const FRIENDS_MESSAGE_PARENT_HEIGHT = 300;
export const FRIENDS_MESSAGE_PARENT_PADDING_X = 25;
export const FRIENDS_MESSAGE_STACK_GAP = 5;
export const FRIENDS_MESSAGE_LABEL_MIN_WIDTH = 50;
export const FRIENDS_MESSAGE_LABEL_PADDING_X = 6;
export const FRIENDS_MESSAGE_MIN_HEIGHT = 25;
export const FRIENDS_BUBBLE_TAIL_WIDTH = 10;
export const FRIENDS_BUBBLE_TAIL_HEIGHT = 6;
export const FRIENDS_SOCIAL_PANEL_BASE_WIDTH = 398;
export const FRIENDS_SOCIAL_PANEL_BASE_HEIGHT = 480;
// Higher backing resolution improves panel legibility without increasing world-space size.
export const FRIENDS_SOCIAL_PANEL_RENDER_SCALE = 4;
export const FRIENDS_FLOATING_CHAT_BASE_WIDTH = 200;
export const FRIENDS_FLOATING_CHAT_BASE_HEIGHT = 300;
export const FRIENDS_FLOATING_CHAT_RENDER_SCALE = 4;
export const FRIENDS_FLOATING_CHAT_PLANE_HEIGHT = 0.91;
export const FRIENDS_FLOATING_CHAT_PLANE_WIDTH =
  (FRIENDS_FLOATING_CHAT_PLANE_HEIGHT * FRIENDS_FLOATING_CHAT_BASE_WIDTH) /
  FRIENDS_FLOATING_CHAT_BASE_HEIGHT;
export const FRIENDS_FLOATING_CHAT_WORLD_SCALE = 5.7375;
export const FRIENDS_RIGHT_CHAT_OFFSET = new THREE.Vector3(1.967075, 2.772, 0.32);
export const FRIENDS_LEFT_CHAT_X_EXTRA_OFFSET = 0.3;
// Visual compensation for icon yaw so left/right anchors read equally distant on screen.
export const FRIENDS_LEFT_CHAT_Z_VISUAL_OFFSET = 0.08;
export const FRIENDS_LEFT_CHAT_OFFSET = new THREE.Vector3(
  -FRIENDS_RIGHT_CHAT_OFFSET.x - FRIENDS_LEFT_CHAT_X_EXTRA_OFFSET,
  FRIENDS_RIGHT_CHAT_OFFSET.y,
  FRIENDS_RIGHT_CHAT_OFFSET.z + FRIENDS_LEFT_CHAT_Z_VISUAL_OFFSET
);
export const FRIENDS_RIGHT_CHAT_TILT_Z = -0.2178;
export const FRIENDS_LEFT_CHAT_TILT_Z = -FRIENDS_RIGHT_CHAT_TILT_Z;
export const FRIENDS_CONVERSATION_INITIAL_DELAY = 0.6;
export const FRIENDS_CONVERSATION_TIME_SCALE = 2.34;
export const FRIENDS_TEXTURE_UPLOAD_FPS = 30;
